export const AGRI_LAND_TYPES = [
  { code: 'NNP', name: 'Nhóm đất nông nghiệp' },
  { code: 'CHN', name: 'Đất trồng cây hằng năm' },
  { code: 'LUA', name: 'Đất trồng lúa' },
  { code: 'LUC', name: 'Đất chuyên trồng lúa' },
  { code: 'LUK', name: 'Đất trồng lúa còn lại' },
  { code: 'HNK', name: 'Đất trồng cây hằng năm khác' },
  { code: 'CLN', name: 'Đất trồng cây lâu năm' },
  { code: 'LNP', name: 'Đất lâm nghiệp' },
  { code: 'RDD', name: 'Đất rừng đặc dụng' },
  { code: 'RPH', name: 'Đất rừng phòng hộ' },
  { code: 'RSX', name: 'Đất rừng sản xuất' },
  { code: 'RSN', name: 'Đất rừng sản xuất là rừng tự nhiên' },
  { code: 'NTS', name: 'Đất nuôi trồng thủy sản' },
  { code: 'CNT', name: 'Đất chăn nuôi tập trung' },
  { code: 'LMU', name: 'Đất làm muối' },
  { code: 'NKH', name: 'Đất nông nghiệp khác' }
];

export const NON_AGRI_LAND_TYPES = [
  { code: 'PNN', name: 'Nhóm đất phi nông nghiệp' },
  { code: 'OTC', name: 'Đất ở' },
  { code: 'ONT', name: 'Đất ở tại nông thôn' },
  { code: 'ODT', name: 'Đất ở tại đô thị' },
  { code: 'TSC', name: 'Đất xây dựng trụ sở cơ quan' },
  { code: 'CQA', name: 'Đất quốc phòng, an ninh' },
  { code: 'CQP', name: 'Đất quốc phòng' },
  { code: 'CAN', name: 'Đất an ninh' },
  { code: 'DSN', name: 'Đất xây dựng công trình sự nghiệp' },
  { code: 'DVH', name: 'Đất xây dựng cơ sở văn hóa' },
  { code: 'DXH', name: 'Đất xây dựng cơ sở xã hội' },
  { code: 'DYT', name: 'Đất xây dựng cơ sở y tế' },
  { code: 'DGD', name: 'Đất xây dựng cơ sở giáo dục và đào tạo' },
  { code: 'DTT', name: 'Đất xây dựng cơ sở thể dục, thể thao' },
  { code: 'DKH', name: 'Đất xây dựng cơ sở khoa học và công nghệ' },
  { code: 'DMT', name: 'Đất xây dựng cơ sở môi trường' },
  { code: 'DKT', name: 'Đất xây dựng cơ sở khí tượng thủy văn' },
  { code: 'DNG', name: 'Đất xây dựng cơ sở ngoại giao' },
  { code: 'DSK', name: 'Đất xây dựng công trình sự nghiệp khác' },
  { code: 'CSK', name: 'Đất sản xuất, kinh doanh phi nông nghiệp' },
  { code: 'SCC', name: 'Đất khu công nghiệp, cụm công nghiệp' },
  { code: 'SKK', name: 'Đất khu công nghiệp' },
  { code: 'SKN', name: 'Đất cụm công nghiệp' },
  { code: 'SCT', name: 'Đất khu công nghệ thông tin tập trung' },
  { code: 'TMD', name: 'Đất thương mại, dịch vụ' },
  { code: 'SKC', name: 'Đất cơ sở sản xuất phi nông nghiệp' },
  { code: 'SKS', name: 'Đất sử dụng cho hoạt động khoáng sản' },
  { code: 'CCC', name: 'Đất sử dụng vào mục đích công cộng' },
  { code: 'DGT', name: 'Đất công trình giao thông' },
  { code: 'DTL', name: 'Đất công trình thủy lợi' },
  { code: 'DCT', name: 'Đất công trình cấp nước, thoát nước' },
  { code: 'DPC', name: 'Đất công trình phòng, chống thiên tai' },
  { code: 'DDD', name: 'Đất có di tích lịch sử - văn hóa, danh lam thắng cảnh, di sản thiên nhiên' },
  { code: 'DRA', name: 'Đất công trình xử lý chất thải' },
  { code: 'DNL', name: 'Đất công trình năng lượng, chiếu sáng công cộng' },
  { code: 'DBV', name: 'Đất công trình hạ tầng bưu chính, viễn thông, công nghệ thông tin' },
  { code: 'DCH', name: 'Đất chợ dân sinh, chợ đầu mối' },
  { code: 'DKV', name: 'Đất khu vui chơi, giải trí công cộng, sinh hoạt cộng đồng' },
  { code: 'TON', name: 'Đất tôn giáo' },
  { code: 'TIN', name: 'Đất tín ngưỡng' },
  { code: 'NTD', name: 'Đất nghĩa trang, nhà tang lễ, cơ sở hỏa táng; đất cơ sở lưu trữ tro cốt' },
  { code: 'TVC', name: 'Đất có mặt nước chuyên dùng' },
  { code: 'MNC', name: 'Đất có mặt nước chuyên dùng dạng ao, hồ, đầm, phá' },
  { code: 'SON', name: 'Đất có mặt nước dạng sông, ngòi, kênh, rạch, suối' }
];
